/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
//defining base address for peripherals
typedef volatile unsigned int  vint32_t ;

#define RCC_BASE 0x40021000
#define PortA_BASE 0x40010800
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE+0x18)
#define GPIO_CRH    *(volatile uint32_t *)(PortA_BASE+0x04)
#define GPIO_ODR    *(volatile uint32_t *)(PortA_BASE+0x0c)
typedef union
{
	vint32_t all_fields ;
	struct
	{
		vint32_t  pin_reserved:13;
		vint32_t  pin13:1;

	}pin;

}R_ODR_t;
int main(void)
{
	volatile R_ODR_t *R_ODR = (volatile R_ODR_t*) GPIO_ODR;

	RCC_APB2ENR|=(1<<2);
	GPIO_CRH&=0XFF0fFFFF;// initialize four bits by zero
	GPIO_CRH|=0X00200000;// set four by 2

	while (1)
	{
		//GPIO_ODR|=(1<<13);// set bit number 13
		R_ODR->pin.pin13=1;
		for (int i=0;i<10000;i++);
		//GPIO_ODR &=~(1<<13);// RESET BIT 13
		R_ODR->pin.pin13=0;
		for (int i=0;i<10000;i++);

	}






	return 0;
}

